version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_ctf
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=kali
      - DB_NAME=ctf_db

  db:
    image: mysql
    container_name: mysql_ctf
    environment:
      MYSQL_ROOT_PASSWORD: kali
      MYSQL_DATABASE: ctf_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
